name: Build Custom Geo Files
on:
  schedule:
    - cron: '0 0 * * *' # Автоматическое обновление каждую ночь
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download Tool and Source Files
        run: |
          # Клонируем исходники утилиты
          git clone https://github.com/hexband/geosite-extract.git
          
          # Скачиваем оригинальные тяжелые базы
          wget -O source-geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget -O source-geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

      - name: Build Tool and Extract Custom Geo Files
        run: |
          # Заходим в папку с утилитой, где лежит go.mod
          cd geosite-extract
          
          # Компилируем напрямую, минуя зависающий прокси proxy.golang.org
          export GOPROXY=direct
          go build -o ../geosite-extract ./cmd/geosite-extract
          
          # Возвращаемся в корневую директорию воркфлоу
          cd ..
          chmod +x geosite-extract
          
          # Вырезаем Geosite (создаст output.dat)
          ./geosite-extract -type geosite -shrink source-geosite.dat category-ru yandex mailru youtube discord telegram instagram tiktok category-ads-all win-spy
          mv output.dat geosite.dat
          
          # Вырезаем Geoip (создаст output.dat)
          ./geosite-extract -type geoip -shrink source-geoip.dat ru private
          mv output.dat geoip.dat

      - name: Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Custom Geo Files
          files: |
            geosite.dat
            geoip.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
